language: node_js
sudo: required
services:
  - docker
node_js:
  - "0.10"
  - "4.4.3"
before_install:
  - npm install -g npm@2.13.5
  - npm install -g grunt-cli
  - npm install -g fh-npm@0.0.9-41
  - sudo apt-get install golang
  - go version
  - curl -L https://github.com/openshift/source-to-image/releases/download/v1.0.9/source-to-image-v1.0.9-f9ff77d-linux-amd64.tar.gz | tar -xz
  - ./s2i build https://github.com/psturc/travis-broken-example openshift/nodejs-010-centos7 sample-test
install: npm install
