language: node_js
sudo: required
services:
  - docker
node_js:
  - "0.10"
  - "4.4.3"
env:
  - TEST="hello"
  - TEST="world"
before_install:
  - npm install -g npm@2.13.5
install: npm install
script: "echo $TEST"
  
